# -*- mode: ruby -*-
# vi: set ft=ruby :

manager_hostname = "debian12"
image_name = "generic/debian12"

Vagrant.configure("2") do |config|
  config.vm.box = "#{image_name}"
  config.vm.hostname = "#{manager_hostname}"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 4
    libvirt.memory = 1024
    libvirt.nested = true
    libvirt.driver = "kvm"
    libvirt.cpu_mode = "host-passthrough"
    libvirt.disk_bus = "virtio"
    libvirt.disk_driver :cache => "writeback"
    libvirt.machine_type = "q35"
    libvirt.nic_model_type = "virtio"
    # libvirt.nvram = "/var/lib/libvirt/qemu/nvram/OVMF_VARS.fd"
  end

  config.vm.provision :ansible do |ansible|
    ansible.verbose = "v"
    ansible.compatibility_mode = "2.0"
#    ansible.extra_vars = { "ansible_python_interpreter" => "/usr/bin/python2" }
    ansible.playbook = "../ansible/playbook.yml"

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    export LANGUAGE=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
    if [ $(systemd-detect-virt) == "kvm" ] ; then apt-get install -y qemu-guest-agent; fi
    swapoff -a
    systemctl disable --now swap.target
    hostname
    cat /etc/os-release
    ip a | grep inet
    echo DONE
  SHELL
end
end