# -*- mode: ruby -*-
# vi: set ft=ruby :

manager_hostname = "msklad12test01"
image_name = "debian/testing64"
# image_name = "alvistack/debian-12"

Vagrant.configure("2") do |config|
  config.vm.box = "#{image_name}"
  config.vm.hostname = "#{manager_hostname}"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 4
    libvirt.memory = 1024
    libvirt.nested = true
    libvirt.driver = "kvm"
    libvirt.cpu_mode = "host-passthrough"
    libvirt.disk_bus = "virtio"
    libvirt.disk_driver :cache => "writeback"
    libvirt.nic_model_type = "virtio"
    libvirt.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio', :disabled => false
    libvirt.serial :type => "pty"
    # Add video type for Rhel10
    libvirt.video_type = "vga"
    libvirt.video_vram = 16384
    # libvirt.nvram = "/var/lib/libvirt/qemu/nvram/OVMF_VARS.fd"
    libvirt.loader = "/usr/share/OVMF/OVMF_CODE.fd"
    libvirt.nvram = "/usr/share/OVMF/OVMF_VARS_4M.fd"
    # For ubuntu
    # libvirt.machine_type = "pc-q35-focal"
    # For rhel 10
    libvirt.machine_type = "q35"
  end

  config.vm.provision :ansible do |ansible|
    ansible.verbose = "v"
    ansible.compatibility_mode = "2.0"
#    ansible.extra_vars = { "ansible_python_interpreter" => "/usr/bin/python2" }
    ansible.playbook = "../ansible/playbook.yml"

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    export LANGUAGE=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
    if [ $(systemd-detect-virt) == "kvm" ] ; then apt-get install -y qemu-guest-agent; fi
    swapoff -a
    systemctl disable --now swap.target
    hostname
    cat /etc/os-release
    ip a | grep inet
    echo DONE
  SHELL
end
end