# -*- mode: ruby -*-
# vi: set ft=ruby :

image_name = "opensuse/Leap-15.5.x86_64"
manager_hostname = "mskomsu15test01"

Vagrant.configure("2") do |config|
  config.vm.box = "#{image_name}"
  config.vm.hostname = "#{manager_hostname}"

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 4
    libvirt.memory = 2048
    libvirt.nested = true
  end

#  config.vm.network :private_network, ip: "192.168.100.124"
#  config.vm.network :forwarded_port, guest: 80, host: 8090, host_ip: "0.0.0.0"

  config.vm.network :public_network,
      :dev => "br0",
      :mode => "bridge",
      :type => "bridge",
      :ip => "192.168.50.234"

  config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant"

  # config.vm.provision "shell", inline: "mkdir -p /home/vagrant/.ssh/"
  # config.vm.provision "file", source: "../ansible/roles/CopyConfig/files/ansible.pub", destination: "/home/vagrant/.ssh/ansible.pub"
  # config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/ansible.pub >> /home/vagrant/.ssh/authorized_keys"

  # config.vm.provision "shell", inline: <<-SHELL
  #   zypper refresh
  #   zypper update -y
  #   zypper install -y htop curl git
  # SHELL

  config.vm.provision :ansible do |ansible|
    ansible.verbose = "v"
    ansible.compatibility_mode = "2.0"
#    ansible.extra_vars = { "ansible_python_interpreter" => "/usr/bin/python2" }
    ansible.playbook = "../ansible/playbook.yml"

  config.vm.provision "shell", run: "once", inline: <<-SHELL
    export LANGUAGE=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
    cat /etc/os-release
    ip route delete default && ip route replace default via 192.168.50.250 metric 11 
    ip a | grep inet
  SHELL

  end
end