# -*- mode: ruby -*-
# vi: set ft=ruby :

manager_hostname = "mskdebian11"
image_name = "generic/debian11"

Vagrant.configure("2") do |config|
  config.vm.box = "#{image_name}"
  config.vm.hostname = "#{manager_hostname}"
  config.vm.network :private_network, ip: "192.168.100.124"
#  config.vm.network :forwarded_port, guest: 80, host: 8090, host_ip: "0.0.0.0"

#  config.vm.network :public_network,
#      :dev => "bridge0",
#      :mode => "bridge",
#      :type => "bridge"
#      :ip=>"192.168.70.221"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.memory = 1024
    libvirt.nested = true
  end

#  config.vm.provision "shell", inline: "mkdir -p /home/vagrant/.ssh/"
#  config.vm.provision "file", source: "../ansible/ansible.pub", destination: "/home/vagrant/.ssh/ansible.pub"
#  config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/ansible.pub >> /home/vagrant/.ssh/authorized_keys"

  config.vm.provision "shell", path: "./provision.sh", run: "once"
  config.vm.provision :ansible do |ansible|
    ansible.verbose = "v"
#    ansible.extra_vars = { "ansible_python_interpreter" => "/usr/bin/python2" }
    ansible.playbook = "../ansible/playbook.yml"

  config.vm.provision "shell", inline: <<-SHELL
    cat /etc/os-release
    ip a | grep inet
  SHELL
end
end

