# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.hostname = "pxeboot"
  config.vm.boot_timeout = 600

  config.vm.define :pxeclient do |pxeclient|
    pxeclient.vm.provider :libvirt do |domain|
      domain.storage :file, :size => '8G', :type => 'qcow2', :cache => 'writeback'
      # domain.boot 'network'      or define a network to boot from, e.g.: 
      boot_network = { 'network' => 'maasnet01' }
      domain.boot boot_network
      domain.boot 'hd'
      domain.cpus = 4
      domain.memory = 2048
      domain.nested = true
      domain.driver = 'kvm'
      domain.cpu_mode = 'host-passthrough'
      # domain.disk_bus = 'virtio'
      domain.machine_type = "q35"
      domain.nic_model_type = 'virtio'
      domain.connect_via_ssh = false
      # Add video type for Rhel10
      domain.video_type = "vga"
      domain.video_vram = 16384
      # Add Serial for qemu agent communication
      domain.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio', :disabled => false
      domain.serial :type => "pty"
      
    end

    # For booting in PXE from existing network, use the following configuration:
    #    pxeclient.vm.network :private_network, libvirt__network_name: "maasnet01"

    # For booting in PXE from a new network, use the following configuration:
    pxeclient.vm.network :private_network,
      type: "dhcp",
      libvirt__network_name: "maasnet01",
      libvirt__network_address: "192.168.95.0",
      libvirt__netmask: "255.255.255.0",
      libvirt__dhcp_start: "192.168.95.2",
      libvirt__dhcp_stop: "192.168.95.254"
    end
end

# Bridge network configuration example:
# Vagrant.configure("2") do |config|
#   config.vm.define :pxeclient do |pxeclient|
#     pxeclient.vm.network :public_network,
#       dev: 'br1',
#       auto_config: false
#     pxeclient.vm.provider :libvirt do |domain|
#       boot_network = {'dev' => 'br1'}
#       domain.storage :file, :size => '100G'
#       domain.boot boot_network
#       domain.boot 'hd'
#     end
#   end
# end