# -*- mode: ruby -*-
# vi: set ft=ruby :

# Change to true if you want to have Docker Swarm ready to work.
auto = ENV['AUTO_START_SWARM'] || true
# Increase numworkers if you want more than 3 nodes
numworkers = 2

# Master memory and CPU configuration
vmmemory = 2048
numcpu = 4

instances = []

(1..numworkers).each do |n|
  instances.push({:name => "msksidb13mk8s0#{n+1}", :ip => "192.168.65.#{n+2}"})
end

# Manager IP and hostname
manager_ip = "192.168.65.2"
manager_hostname = "msksidb13mk8s01"

File.open("./hosts", 'w') { |file|
  file.write("#{manager_ip} #{manager_hostname} #{manager_hostname}\n")
  instances.each do |i|
    file.write("#{i[:ip]} #{i[:name]} #{i[:name]}\n")
  end
  }

Vagrant.configure("2") do |config|
    config.vm.define "msksidb13mk8s01" do |i|
      i.vm.provider :libvirt do |libvirt|
        libvirt.cpus = "#{numcpu}"
        libvirt.memory = "#{vmmemory}"
        libvirt.nested = true
        libvirt.driver = "kvm"
        libvirt.disk_bus = "virtio"
        libvirt.disk_driver :cache => "writeback"
        libvirt.machine_type = "q35"
        libvirt.nic_model_type = "virtio"
        libvirt.cpu_mode = "host-passthrough"
        # libvirt.storage :file, :size => '60G', :type => 'qcow2', :cache => 'writeback', :pool => 'ssdpool'
        libvirt.storage_pool_name = "ssdpool"
        libvirt.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio', :disabled => false
        libvirt.serial :type => "pty"
      end
      i.vm.box = "debian/trixie64"
      i.vm.hostname = "#{manager_hostname}"

      i.vm.network :public_network,
        :dev => "br0",
        :mode => "bridge",
        :type => "bridge",
        :ip => "192.168.50.120",
        :autostart => "true"

      i.vm.network :private_network, :ip => "#{manager_ip}", :autostart => "true"
      i.vm.synced_folder ".", "/vagrant", 
          # owner: "vagrant", group: "vagrant" ### Enable for Redhat based systems
         type: "nfs" ### Enable for Ubuntu based systems
        #  nfs_version: 4, ### Enable for Ubuntu based systems
        #  nfs_udp: false  ### Enable for Ubuntu based systems

      if File.file?("./hosts")
        i.vm.provision "file", source: "hosts", destination: "/tmp/hosts"
        i.vm.provision "shell", inline: "cat /tmp/hosts >> /etc/hosts", privileged: true
      end

#      i.vm.provision "file", source: "~/.ssh/id.rsa.pub", destination: "~/.ssh/me.pub"
#      i.vm.provision "shell", inline: <<-SHELL
#         mkdir -p /home/vagrant/.ssh/
#         touch /home/vagrant/.ssh/authorized_keys
#         cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
#      SHELL

      i.vm.provision "shell", inline: "mkdir -p /home/vagrant/.ssh/"
      i.vm.provision "file", source: "../ansible/ansible.pub", destination: "/home/vagrant/.ssh/ansible.pub"
      i.vm.provision "shell", inline: "cat /home/vagrant/.ssh/ansible.pub >> /home/vagrant/.ssh/authorized_keys"

      i.vm.provision :ansible do |ansible|
        ansible.verbose = "v"
        # ansible.compatibility_mode = "2.0"
    #    ansible.extra_vars = { "ansible_python_interpreter" => "/usr/bin/python3" }
        ansible.playbook = "../ansible/playbook.yml"
      end

      i.vm.provision "shell", path: "./provision.sh", run: "once"

      if auto
        i.vm.provision "shell", inline: "microk8s add-node --token $(cat /vagrant/token) --format short --token-ttl 1200 | grep #{manager_ip} > /vagrant/microk8s.join && sed -i 's|^microk8s join *||' /vagrant/microk8s.join && sed -i 's/$/ --worker/' /vagrant/microk8s.join"
      end
end

instances.each do |instance|
    config.vm.define instance[:name] do |i|
      i.vm.provider :libvirt do |lv|
          lv.cpus = 4
          lv.memory = 1024
          lv.nested = true
          lv.driver = "kvm"
          lv.disk_bus = "virtio"
          lv.disk_driver :cache => "writeback"
          lv.machine_type = "q35"
          lv.nic_model_type = "virtio"
          lv.cpu_mode = "host-passthrough"
          lv.storage_pool_name = "ssdpool"
          lv.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio', :disabled => false
          lv.serial :type => "pty"
      end
      i.vm.box = "debian/trixie64"
      i.vm.hostname = instance[:name]
      i.vm.network :private_network, ip: "#{instance[:ip]}"
 
      i.vm.synced_folder ".", "/vagrant",
          # owner: "vagrant", group: "vagrant" ### Enable for Redhat based systems
          type: "nfs"  ### Enable for Ubuntu based systems
        #  nfs_version: 4, ### Enable for Ubuntu based systems
        #  nfs_udp: false  ### Enable for Ubuntu based systems
 
      if File.file?("./hosts")
        i.vm.provision "file", source: "hosts", destination: "/tmp/hosts"
        i.vm.provision "shell", inline: "cat /tmp/hosts >> /etc/hosts", privileged: true
      end
 
      i.vm.provision "shell", inline: "mkdir -p /home/vagrant/.ssh/"
      i.vm.provision "file", source: "../ansible/roles/CopyConfig/files/ansible.pub", destination: "/home/vagrant/.ssh/ansible.pub"
      i.vm.provision "shell", inline: "cat /home/vagrant/.ssh/ansible.pub >> /home/vagrant/.ssh/authorized_keys"
 
      i.vm.provision :ansible do |ansible|
        ansible.verbose = "v"
        # ansible.compatibility_mode = "2.0"
     #   ansible.extra_vars = { "ansible_python_interpreter" => "/usr/bin/python3" }
        ansible.playbook = "../ansible/playbook.yml"
      end

      i.vm.provision "shell", path: "./provision.sh", run: "once"
 
      if auto
        i.vm.provision "shell", inline: "/usr/sbin/microk8s join $(cat /vagrant/microk8s.join)"
      end
end
end
end