# -*- mode: ruby -*-
# vi: set ft=ruby :

# Change to true if you want to have Kubernetes ready to work.
auto = ENV['AUTO_START_K8S'] || true

# Increase numworkers if you want more nodes
numworkers = 2

# Master memory and CPU configuration
vmmemory = 2048
numcpu = 4

instances = []

(1..numworkers).each do |n|
  instances.push({:name => "k8snode#{n}", :ip => "192.168.63.#{n+2}"})
end

manager_ip = "192.168.63.2"
manager_hostname = "k8smaster"

File.open("./hosts", 'w') { |file|
  file.write("#{manager_ip} #{manager_hostname} #{manager_hostname}\n")
  instances.each do |i|
    file.write("#{i[:ip]} #{i[:name]} #{i[:name]}\n")
  end
  }

# Old proxy configuration
# http_proxy = ""
# Proxy configuration
# if ENV['http_proxy']
#       http_proxy = ENV['http_proxy']
#         https_proxy = ENV['https_proxy']
# end

# no_proxy = "localhost,127.0.0.1,#{manager_ip}"
# instances.each do |instance|
#     no_proxy += ",#{instance[:ip]}"
# end

Vagrant.configure("2") do |config|
    config.vm.define "k8smaster" do |i|
      i.vm.provider :libvirt do |libvirt|
        libvirt.cpus = ${numcpu}
        libvirt.memory = ${vmmemory}
        libvirt.nested = true
        libvirt.name = "#{manager_hostname}"
        libvirt.driver = "kvm"
        libvirt.cpu_mode = "host-passthrough"
        libvirt.disk_bus = "virtio"
        libvirt.disk_driver :cache => "writeback"
        libvirt.machine_type = "q35"
        libvirt.nic_model_type = "virtio"
      end
        i.vm.box = "roboxes-x64/debian12"
        i.vm.hostname = "#{manager_hostname}"

        i.vm.network :public_network,
            :dev => "br0",
            :mode => "bridge",
            :type => "bridge",
            :ip => "192.168.50.238",
            :autostart => "true"

        i.vm.network :private_network, :ip => "#{manager_ip}", :autostart => "true"
        i.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant", nfs_udp: false
#          type: "nfs",
#          nfs_version: 4,
#          nfs_udp: false
        if File.file?("./hosts")
          i.vm.provision "file", source: "hosts", destination: "/tmp/hosts"
          i.vm.provision "shell", inline: "cat /tmp/hosts >> /etc/hosts", privileged: true
        end

      i.vm.provision "shell", inline: "mkdir -p /home/vagrant/.ssh/"
      i.vm.provision "file", source: "../ansible/ansible.pub", destination: "/home/vagrant/.ssh/ansible.pub"
      i.vm.provision "shell", inline: "cat /home/vagrant/.ssh/ansible.pub >> /home/vagrant/.ssh/authorized_keys"

      i.vm.provision :ansible do |ansible|
        ansible.verbose = "vv"
        ansible.compatibility_mode = "2.0"
    #    ansible.extra_vars = { "ansible_python_interpreter" => "/usr/bin/python3" }
        ansible.playbook = "../ansible/playbook.yml"

      i.vm.provision "shell", path: "./provision.sh", run: "once"

    if auto
       i.vm.provision "shell", path: "./provisionk8smaster.sh", run: "once"
    end
end
end

instances.each do |instance|
    config.vm.define instance[:name] do |i|
     i.vm.provider :libvirt do |lv|
         lv.cpus = 4
         lv.memory = 2048
         lv.nested = true
         lv.driver = "kvm"
         lv.cpu_mode = "host-passthrough"
         lv.disk_bus = "virtio"
         lv.disk_driver :cache => "writeback"
         lv.machine_type = "q35"
         lv.nic_model_type = "virtio"
     end
     i.vm.box = "roboxes-x64/debian12"
     i.vm.hostname = instance[:name]
     i.vm.network :private_network, ip: "#{instance[:ip]}"

     i.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant", nfs_udp: false

     if File.file?("./hosts")
       i.vm.provision "file", source: "hosts", destination: "/tmp/hosts"
       i.vm.provision "shell", inline: "cat /tmp/hosts >> /etc/hosts", privileged: true
     end

     i.vm.provision :ansible do |ansible|
       ansible.verbose = "vv"
       ansible.compatibility_mode = "2.0"
    #   ansible.extra_vars = { "ansible_python_interpreter" => "/usr/bin/python3" }
       ansible.playbook = "../ansible/playbook.yml"

     i.vm.provision "shell", path: "./provision.sh", run: "once"

    # If you forgot about vagrant up --no-parallel
     i.vm.provision "shell", inline: "sleep 10"

    if auto
      i.vm.provision "shell", path: "./provisionk8snodes.sh", run: "once"
      i.vm.provision "shell", inline: "kubeadm join #{manager_ip}:6443 --token $(cat /vagrant/kubeadm_join) --discovery-token-ca-cert-hash sha256:$(cat /vagrant/ca_cert_hash)"
    end
end
end
end
end