---
# - hosts: centos
#   tasks:
   - name: install packages on Ubuntu or Debian
     apt: 
       pkg: ['mc', 'htop', 'curl', 'wget']
     become: yes
     when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  
   - name: Install Packages on Centos
     yum:
       pkg: ['mc', 'mtr', 'curl', 'htop', 'nano', 'wget']
     become: yes
     when: ansible_distribution == "CentOS"

   - name: Install Packages on Oracle
     dnf:
       pkg: ['mc', 'curl', 'htop', 'nano', 'wget']
     become: yes
     when: ansible_distribution == "OracleLinux" or ansible_distribution == "RedHat"

   - name: Install Packages on OpenSuse or SLES
     zypper:
       pkg: ['curl', 'htop', 'nano', 'git']
     become: yes
     when: ansible_distribution == "SLES" or ansible_distribution_file_variety == "SUSE"
