# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version.
VAGRANTFILE_API_VERSION = "2"

# Box metadata location and box name
BOX_URL = "https://oracle.github.io/vagrant-projects/boxes"
BOX_NAME = "oraclelinux/9"

ui = Vagrant::UI::Prefixed.new(Vagrant::UI::Colored.new, "vagrant")

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = BOX_NAME
  config.vm.box_url = "#{BOX_URL}/#{BOX_NAME}.json"
  config.vm.define "msksiol9test01"
  config.vm.hostname = "msksiol9test01"
  config.vm.provider :libvirt do |v|
    v.cpus = 4
    v.memory = 2048
    v.nested = true
    v.disk_bus = "virtio"
    v.disk_driver :cache => "writeback"
    v.driver = "kvm"
    v.machine_type = "q35"
    v.cpu_mode = "host-passthrough"
    v.nic_model_type = "virtio"
  end

  config.vm.network :public_network,
    :dev => "br0",
    :mode => "bridge",
    :type => "bridge",
    :ip => "192.168.50.235"

  config.vm.synced_folder ".", "/vagrant",
    # owner: "vagrant", group: "vagrant"
    type: "nfs",
    nfs_version: 4,
    nfs_udp: false

  config.vm.provision "shell", inline: <<-SHELL
    cat /etc/os-release
    echo LANG=en_US.utf-8 >> /etc/environment
    echo LC_ALL=en_US.utf-8 >> /etc/environment
    timedatectl set-timezone Europe/Warsaw
    dnf update -y && dnf -y install container-tools oracle-epel-release-el9
    nmcli connection modify 'eth0' ipv4.never-default true
    nmcli connection modify 'System eth1' ipv4.routes "0.0.0.0/0 192.168.50.250 10"
    nmcli connection modify 'System eth1' ipv4.route-metric 10
    nmcli connection modify 'System eth1' ipv4.gateway "192.168.50.250"
    nmcli c down 'System eth1' && nmcli c up 'System eth1'
    # ip route delete default && ip route replace default via 192.168.50.250 metric 11
    ip a | grep inet
  SHELL

  # Provision everything on the first run
  # config.vm.provision "shell", path: "scripts/install.sh"
  # if Vagrant.has_plugin?("vagrant-reload")
  #   config.vm.provision "shell", inline: "echo 'Reloading your VM to activate the latest kernel'"
  #   config.vm.provision :reload
  # else
  #   config.vm.provision "shell", inline: "echo 'You need to reload your VM to activate the latest kernel'"
  # end

  config.vm.provision "shell", inline: "echo 'INSTALLER: Installation complete, Oracle Linux 9 ready to use!'"

end