# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/freebsd-13"
  config.vm.hostname = "freebsd13"

#  config.vm.network "public_network", bridge: "enp2s0f0"
#  config.vm.network :private_network, ip: "192.168.121.190"
#  config.vm.network :private_network, :ip => "192.168.122.200"
#  config.vm.network :forwarded_port, guest: 80, host: 8090, host_ip: "0.0.0.0"

  config.vm.network :public_network,
      :dev => "br0",
      :mode => "bridge",
      :type => "bridge",
      :ip => "192.168.50.233"

  config.vm.synced_folder ".", "/vagrant",
    # owner: "vagrant", group: "vagrant"
    # Working setting for RHEL10
    type: "nfs",
    nfs_version: 4,
    nfs_udp: false 

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 4
    libvirt.memory = 1024
    libvirt.nested = true
    libvirt.video_type = "vga"
    libvirt.video_vram = 16384
    libvirt.machine_type = "q35"
  end

  config.vm.provision "shell", inline: "mkdir -p /home/vagrant/.ssh/"
  config.vm.provision "file", source: "../ansible/roles/CopyConfig/files/ansible.pub", destination: "/home/vagrant/.ssh/ansible.pub"
  config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/ansible.pub >> /home/vagrant/.ssh/authorized_keys"

  config.vm.provision "shell", run: "once", inline: <<-SHELL
    pkg update
    pkg upgrade -y
    pkg install -y mc htop nano bash
    uname -a
    ifconfig | grep inet
  SHELL

end
