---
- hosts: all
  vars:
      username: vmadmin

  roles:
  - Update
  - EpelRelease
  - PackageInstall
#  - CopyConfig
  - Usersconfig
  - CreateUser
#  - RestartMachines
- hosts: debian12
  roles:
  - Hardening
