---
- hosts: all
  roles:
  - Update
  - CopyConfig
  - EpelRelease
  - PackageInstall
  - Usersconfig
#  - RestartMachines
- hosts: debian11awx
  roles:
  - Hardening
# - hosts: dm, dw1, dw2
#  roles:
#  - DockerInstall
