---
- hosts: all
  vars:
    username: madmin

  roles:
  - Update
  - EpelRelease
  - PackageInstall
  - CreateUser
  - CopyConfig
  - Usersconfig
#  - RestartMachines
- hosts: msklad12test01
  roles:
  - Hardening
