---
- hosts: all
  vars:
    username: madmin

  roles:
  - Update
  - EpelRelease
  - PackageInstall
  - CopyConfig
  - Usersconfig
  - CreateUser
#  - RestartMachines
- hosts: debian12
  roles:
  - Hardening
