---
- hosts: all
  roles:
  - Update
  - EpelRelease
  - PackageInstall
#  - CopyConfig
  - Usersconfig
  - CreateUser
    vars:
      username: vmadmin
#  - RestartMachines
- hosts: debian12
  roles:
  - Hardening
