# NOTE01: Be sure to modify your /etc/ansible/hosts file to include your hosts!
# NOTE02: Be sure to ssh-add private key!
---
# gather_facts: yes
  - name: Upgrade all installed packages for Debian and Ubuntu
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
      autoclean: yes
      autoremove: yes
    become: yes
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: Upgrade all installed packages for CentOS
    yum:
      name: '*'
      state: latest
    become: yes
    when: ansible_distribution == "CentOS"

  - name: Upgrade all installed packages for Oracle or RedHat or Alma Linux
    dnf:
      name: '*'
      state: latest
    become: yes
    when: ansible_distribution == "OracleLinux" or ansible_distribution == "RedHat" or ansible_distribution == "AlmaLinux"
#   when: ansible_facts['os_family'] == 'OracleLinux' and ansible_facts ['distribution_major_version'] == '8'

  - name: Upgrade all installed packages for openSUSE or SLES
    zypper:
      name: '*'
      state: latest
    become: yes
    when: ansible_distribution == "SLES" or ansible_distribution_file_variety == "SUSE"
