# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "mskomce7test01"
#  config.vm.network :private_network, ip: "192.168.100.124"
#  config.vm.network :forwarded_port, guest: 80, host: 8090, host_ip: "0.0.0.0"

  config.vm.network :public_network,
      :dev => "br0",
      :mode => "bridge",
      :type => "bridge",
      :ip => "192.168.50.231"

  config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant"

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.memory = 1024
    libvirt.nested = true
    libvirt.cpu_mode = "host-passthrough"
    # libvirt.cputopology :sockets => '2', :cores => '2', :threads => '1'
  end

  config.vm.provision "shell", inline: <<-SHELL
    timedatectl set-timezone Europe/Warsaw
    echo LANG=en_US.utf-8 >> /etc/environment
    echo LC_ALL=en_US.utf-8 >> /etc/environment
#    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
    yum update -y
    yum install gcc make perl kernel-devel -y
    yum install epel-release -y
#    yum install -y httpd
#    systemctl enable --now httpd.service
    cat /etc/os-release
    ip a | grep inet
  SHELL
end
