# -*- mode: ruby -*-
# vi: set ft=ruby :

vmhostname = "msklacen7test01"
vmip = "192.168.50.244"

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "#{vmhostname}"
#  config.vm.network :private_network, ip: "192.168.100.124"
#  config.vm.network :forwarded_port, guest: 80, host: 8090, host_ip: "0.0.0.0"

  config.vm.network :public_network,
      :dev => "br0",
      :mode => "bridge",
      :type => "bridge",
      :ip => "#{vmip}"

  config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant"

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.memory = 1024
    libvirt.nested = true
    libvirt.cpu_mode = "host-passthrough"
    libvirt.video_type = "vga"
    libvirt.video_vram = 16384
    libvirt.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio', :disabled => false
    libvirt.serial :type => "pty"
    # libvirt.cputopology :sockets => '2', :cores => '2', :threads => '1'
  end

  # Enable Archive repos for CentOS 7 and EPEL
  config.vm.provision "shell", path: "provision.sh", run: "once"

  config.vm.provision "shell", inline: <<-SHELL
    echo LANG=en_US.utf-8 >> /etc/environment
    echo LC_ALL=en_US.utf-8 >> /etc/environment

    timedatectl set-timezone Europe/Warsaw

    # Turn off swap and remove swapfile
    swapoff -a
    systemctl stop swap.target
    systemctl mask swap.target
    rm -f /swapfile
    sed -i '/swap/s/^/#/' /etc/fstab

    yum update -y
    yum remove -y open-vm-tools
    yum install gcc make perl htop mtr kernel-devel qemu-guest-agent -y
    # yum install epel-release -y
    # yum install -y httpd
    # systemctl enable --now httpd.service

    # Enable routing on eth1 and disable default route on eth0
    nmcli connection modify 'System eth0' ipv4.never-default yes
    systemctl enable --now serial-getty@ttyS0.service

    cat /etc/os-release
    ip a | grep inet
  SHELL

end
