# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "mskcentos7"
  config.vm.network :private_network, ip: "192.168.100.124"

#  config.vm.network :forwarded_port, guest: 80, host: 8090, host_ip: "0.0.0.0"

#  config.vm.network :public_network,
#      :dev => "bridge0",
#      :mode => "bridge",
#      :type => "bridge"
#      :ip=>"192.168.70.221"

  config.vm.synced_folder ".", "/vagrant_data", disabled: true

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.memory = 2048
    libvirt.nested = true
  end

  config.vm.provision "shell", inline: <<-SHELL
#    yum update -y
#    yum install -y httpd
#    systemctl enable --now httpd.service
    cat /etc/os-release
    ip a | grep inet
  SHELL
end
